services:
  app:
    build: .
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ./certs/:/app/certs/
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_SSL_ENABLED: true
      SERVER_PORT: 8443
      SERVER_SSL_KEY_STORE: classpath:/certs/server.jks
      SERVER_SSL_KEY_STORE_TYPE: JKS
      SERVER_SSL_KEY_STORE_PASSWORD: changeit
      SERVER_SSL_KEY_ALIAS: server
    healthcheck:
      test: ["CMD", "sh", "-c", "curl --insecure --fail https://localhost:8443 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30